### PR TITLE
Replaces prompts with dialog

### PR DESCRIPTION
**Pull request by mcanoy**
This PR includes a replacement for the dialog boxes on the internal page which gather additional data to kick off PBI

There is now a dialog box when click on the build label which asks for info for
- GitHub Repo
- Project Name
- Username
- Password

Each field is required and may not be empty

This PR has included the vex js for the dialog box which is around 7k. Only loaded on internal.

screen shot 2017-02-16 at 10 36 54 pm

### CODE REVIEW

**Comment by mcanoy** [comment]
@oybed @mwalker5000 Updated to remove SHA1 and add username. Added validation to ensure all fields had some value. Updated screenshot in PR description

**Comment by oybed** [comment]
@mcanoy great - thank you. Will test it out and let you know how it goes.

**Comment by mcanoy** [comment]
@oybed all changes in place from this morning

screen shot 2017-02-28 at 3 23 36 pm

**Comment by oybed** [comment]
@mcanoy LGTM ... will merge

**Pull request merged**
