### PR TITLE
Adding new content to the DevOps section

### PR DESCRIPTION
**Pull request by oybed**
Adding:
- Tekton
- Zoom
- Google Meet
- Bluejeans
- WhatsApp
+ moving Jira to a new category

### CODE REVIEW

**Comment by oybed** [comment]
@lallmon mind giving this a review?

**Review by lallmon — APPROVED** [review]
Looks good to me. :rocket: 

Any reason why widths are 24.5%? Losing 2% to some other CSS magic numbers? :smile:

**Comment by oybed** [comment]
24.5% is aligning with existing widths (used above in the app dev section).

**Comment by lallmon** [comment]
Are we merging our own PR or would you like to? :play_or_pause_button:

**Comment by oybed** [comment]
If you are good with this PR, please merge. We can discuss, but not merging our own PRs.

**Pull request merged**
